import { useEffect, useState } from 'react';
import { command, getSnapshot, socketUrl } from './api/client';
import { DebugPanel } from './components/DebugPanel'; import { EventStream } from './components/EventStream'; import { SocialGraphView } from './components/SocialGraphView';
import type { Snapshot } from './types/api'; import './styles.css';
const empty: Snapshot={state:{step:0,running:false,oasisStatus:'uninitialized',llmStatus:'unknown',activeAgentIds:[],totalEvents:0,llmRequestCount:0,errorCount:0},agents:[],graph:[],events:[]};
export default function App() { const [snapshot,setSnapshot]=useState(empty); const [ws,setWs]=useState('CONNECTING'); const [error,setError]=useState('');
useEffect(()=>{getSnapshot().then(setSnapshot).catch(error=>setError(error.message)); const socket=new WebSocket(socketUrl); socket.onopen=()=>setWs('CONNECTED'); socket.onclose=()=>setWs('DISCONNECTED'); socket.onmessage=message=>{const packet=JSON.parse(message.data); if(packet.type==='snapshot')setSnapshot(packet.data); if(packet.type==='event')setSnapshot(previous=>({...previous,events:[...previous.events,packet.data]}));}; return()=>socket.close();},[]);
const run=async(name:'start'|'pause'|'resume'|'step')=>{try{setSnapshot(await command(name));setError('')}catch(error){setError(error instanceof Error?error.message:'Command failed')}};
return <main><header><div><p className="eyebrow">EXPERIMENT 001</p><h1>OASIS / LIVING SOCIAL NETWORK</h1><p className="subtitle">An observer for autonomous social-platform dynamics — not a physical world.</p></div><div className="status"><span className={snapshot.state.running?'pulse':''}/>{snapshot.state.running?'RUNNING':'STANDBY'} · STEP {snapshot.state.step}</div></header><nav><button onClick={()=>run('start')}>Start</button><button onClick={()=>run('pause')}>Pause</button><button onClick={()=>run('resume')}>Resume</button><button className="ghost" onClick={()=>run('step')}>Step once</button>{error&&<output>{error}</output>}</nav><div className="dashboard"><SocialGraphView agents={snapshot.agents} graph={snapshot.graph} active={snapshot.state.activeAgentIds}/><DebugPanel state={snapshot.state} ws={ws}/><EventStream events={snapshot.events}/></div><footer>20 fixed presentation nodes · Follow edges persist · OASIS trace events stream live</footer></main> }
