import { useEffect, useState } from 'react';
import { command, getSnapshot, mockMode, socketUrl, subscribeMock } from './api/client';
import { advance } from './api/mock';
import { DebugPanel } from './components/DebugPanel'; import { EventStream } from './components/EventStream'; import { SocialGraphView } from './components/SocialGraphView';
import type { Snapshot } from './types/api'; import './styles.css';
import { useI18n } from './i18n';
import { Version2App } from './ui/Version2App';
import { AgentInspector } from './components/AgentInspector';
const empty: Snapshot={state:{step:0,running:false,oasisStatus:'uninitialized',llmStatus:'unknown',activeAgentIds:[],totalEvents:0,llmRequestCount:0,errorCount:0},agents:[],graph:[],events:[]};
function Version1App() { const { t, toggleLocale }=useI18n(); const [snapshot,setSnapshot]=useState(empty); const [ws,setWs]=useState('CONNECTING'); const [error,setError]=useState(''); const [selectedAgentId,setSelectedAgentId]=useState<number|undefined>(()=>{const value=new URLSearchParams(location.search).get('agent');return value?Number(value):undefined}); const [selectedEventId,setSelectedEventId]=useState<string>();
useEffect(()=>{getSnapshot().then(setSnapshot).catch(error=>setError(error.message)); if(mockMode){setWs('MOCK'); const unsubscribe=subscribeMock(setSnapshot); const timer=window.setInterval(advance,4000); return()=>{unsubscribe();window.clearInterval(timer)}} const socket=new WebSocket(socketUrl); socket.onopen=()=>setWs('CONNECTED'); socket.onclose=()=>setWs('DISCONNECTED'); socket.onmessage=message=>{const packet=JSON.parse(message.data); if(packet.type==='snapshot')setSnapshot(packet.data); if(packet.type==='event')setSnapshot(previous=>({...previous,events:[...previous.events,packet.data]}));}; return()=>socket.close();},[]);
const run=async(name:'start'|'pause'|'resume'|'step')=>{try{setSnapshot(await command(name));setError('')}catch(error){setError(error instanceof Error?error.message:'Command failed')}};
const selectAgent=(id:number|undefined)=>{setSelectedAgentId(id);const url=new URL(location.href);id===undefined?url.searchParams.delete('agent'):url.searchParams.set('agent',String(id));history.replaceState(null,'',url)}; useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement)return;if(event.key==='Escape')selectAgent(undefined);if(event.key==='/' ){event.preventDefault();document.querySelector<HTMLInputElement>('.event-tools input')?.focus()}if(event.key==='s'||event.key==='S')run('step');if(event.key===' '){event.preventDefault();run(snapshot.state.running?'pause':'start')}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[snapshot.state.running]);
return <main><header><div><p className="eyebrow">{t('experiment')} {mockMode && <mark>{t('mockData')}</mark>}</p><h1>{t('title')}</h1><p className="subtitle">{t('subtitle')}</p></div><div className="status"><span className={snapshot.state.running?'pulse':''}/>{snapshot.state.running?t('running'):t('standby')} · {t('step')} {snapshot.state.step}</div></header><nav><button onClick={()=>run('start')}>{t('start')}</button><button onClick={()=>run('pause')}>{t('pause')}</button><button onClick={()=>run('resume')}>{t('resume')}</button><button className="ghost" onClick={()=>run('step')}>{t('stepOnce')}</button><button className="language" onClick={toggleLocale}>{t('language')}</button>{error&&<output>{error}</output>}</nav><div className="dashboard"><SocialGraphView agents={snapshot.agents} graph={snapshot.graph} active={snapshot.state.activeAgentIds} selectedAgentId={selectedAgentId} onSelectAgent={selectAgent}/><DebugPanel state={snapshot.state} ws={ws}/><AgentInspector snapshot={snapshot} agentId={selectedAgentId} onClose={()=>selectAgent(undefined)}/><EventStream events={snapshot.events} selectedEventId={selectedEventId} onSelectAgent={selectAgent} onSelectEvent={event=>setSelectedEventId(event.id)}/></div><footer>{t(mockMode ? 'footerMock' : 'footerReal')}</footer></main> }

export default function App() { return import.meta.env.VITE_UI_VERSION === 'version2' ? <Version2App /> : <Version1App />; }
